// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY64pw3U9I6Hidx0Cao6VP8mNWEpYQIO4',
    appId: '1:746458534934:web:4bd32197625d629b159137',
    messagingSenderId: '746458534934',
    projectId: 'parent-portal-app-36b77',
    authDomain: 'parent-portal-app-36b77.firebaseapp.com',
    databaseURL: 'https://parent-portal-app-36b77.firebaseio.com',
    storageBucket: 'parent-portal-app-36b77.appspot.com',
    measurementId: 'G-0RHL3T16MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-B7jICiNpUde4wwWbqbZeoVyt1pjXDQ8',
    appId: '1:746458534934:android:745ce7d3dd39cb99159137',
    messagingSenderId: '746458534934',
    projectId: 'parent-portal-app-36b77',
    databaseURL: 'https://parent-portal-app-36b77.firebaseio.com',
    storageBucket: 'parent-portal-app-36b77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilwwc3gaCMD72UcGX4Ap9KUkSn8_1abc',
    appId: '1:746458534934:ios:84c1a2fd87c209bd159137',
    messagingSenderId: '746458534934',
    projectId: 'parent-portal-app-36b77',
    databaseURL: 'https://parent-portal-app-36b77.firebaseio.com',
    storageBucket: 'parent-portal-app-36b77.appspot.com',
    androidClientId: '746458534934-95fb0u6f19qagurf0ni2l9ijquc1k991.apps.googleusercontent.com',
    iosClientId: '746458534934-e5ba5c15taeqa315bo8np1r9h7pmk6rl.apps.googleusercontent.com',
    iosBundleId: 'com.calms.calms-parent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilwwc3gaCMD72UcGX4Ap9KUkSn8_1abc',
    appId: '1:746458534934:ios:d38ab97176d56b56159137',
    messagingSenderId: '746458534934',
    projectId: 'parent-portal-app-36b77',
    databaseURL: 'https://parent-portal-app-36b77.firebaseio.com',
    storageBucket: 'parent-portal-app-36b77.appspot.com',
    androidClientId: '746458534934-95fb0u6f19qagurf0ni2l9ijquc1k991.apps.googleusercontent.com',
    iosClientId: '746458534934-j78rne81b4d9k1digp0md6r0hbs398db.apps.googleusercontent.com',
    iosBundleId: 'com.example.calmsParentLatest',
  );
}
